services:
  mariadb:
    image: mariadb:10.5
    container_name: rerekisho-reaction-mariadb-local
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: rerekisho_reaction_app
      MARIADB_USER: prisma_user_local
      MARIADB_PASSWORD: passpass
      TZ: Asia/Tokyo
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data: